name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  MAJOR_NUM: '1'
  MINOR_NUM: '0'
  PATCH_NUM: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    # Scan directoris & files
    - uses: actions/checkout@v3
   
    - name: Build the Docker image
      run: docker build --build-arg PATCH_NUM=$PATCH_NUM --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t java_project:latest .
      
    - name: show_image
      run: docker images
      
    - name: run_image
      run: docker run --name project java_project:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_T }}     
        
    - name: tag latest
      run: docker tag hello:latest vova0911/project:latest
    
    - name: tag version
      run: docker tag hello:latest vova0911/project:$MAJOR_NUM.$MINOR_NUM.$PATCH_NUM 
      
    - name: push latest
      run: docker push vova0911/project:latest
      
    - name: push version
      run: docker push vova0911/project:$MAJOR_NUM.$MINOR_NUM.$PATCH_NUM 
      
      
